version: "3"
services:
    parity:
        image: keydonix/parity-instantseal-maker
        ports:
            - "1235:8545"
    deploy:
        build: ./contracts
        environment:
            - ETHEREUM_HTTP=http://parity:8545
            - ETHEREUM_GAS_PRICE_IN_NANOETH=1
            - ETHEREUM_PRIVATE_KEY=fae42052f82bed612a724fec3632f325f377120592c75bb78adfcceae6470c5a
            - ETHEREUM_OASIS_ADDRESS=0x3c6721551c2ba3973560aef3e11d34ce05db4047
            - ETHEREUM_MAKER_ADRESS=0x93943fb2d02ce1101dadc3ab1bc3cab723fd19d6
        links:
            - parity
    client:
        build: ./client
        ports:
            - "1234:80"
