version: "3"
services:
    parity:
        image: keydonix/parity-instantseal-node8
        ports:
            - "1235:8545"
    deploy:
        build: ./contracts
        environment:
            - ETHEREUM_HTTP=http://parity:8545
            - ETHEREUM_GAS_PRICE_IN_NANOETH=1
            - ETHEREUM_PRIVATE_KEY=fae42052f82bed612a724fec3632f325f377120592c75bb78adfcceae6470c5a
            - ETHEREUM_OASIS_ADDRESS=0000000000000000000000000000000000000000
            - ETHEREUM_MAKER_ADRESS=0000000000000000000000000000000000000000
        links:
            - parity
    client:
        build: ./client
        ports:
            - "1234:80"
