version: "3"
services:
    parity:
        build:
            context: ./contracts
            dockerfile: ./Dockerfile-Parity
            args:
                - ETHEREUM_HTTP=http://localhost:8545
                - ETHEREUM_GAS_PRICE_IN_NANOETH=1
                - ETHEREUM_PRIVATE_KEY=fae42052f82bed612a724fec3632f325f377120592c75bb78adfcceae6470c5a
                - ETHEREUM_OASIS_ADDRESS=0x3c6721551c2ba3973560aef3e11d34ce05db4047
                - ETHEREUM_MAKER_ADRESS=0x93943fb2d02ce1101dadc3ab1bc3cab723fd19d6
        ports:
            - "1235:8545"

    geth:
        build:
            context: ./contracts
            dockerfile: ./Dockerfile-Geth
            args:
                - ETHEREUM_HTTP=http://localhost:8545
                - ETHEREUM_GAS_PRICE_IN_NANOETH=1
                - ETHEREUM_PRIVATE_KEY=fae42052f82bed612a724fec3632f325f377120592c75bb78adfcceae6470c5a
                - ETHEREUM_OASIS_ADDRESS=0x3c6721551c2ba3973560aef3e11d34ce05db4047
                - ETHEREUM_MAKER_ADRESS=0x93943fb2d02ce1101dadc3ab1bc3cab723fd19d6
        environment:
            - GETH_VERBOSITY=2
        ports:
            - "1236:8545"

    client-library-parity:
        build: ./client-library
        links:
            - parity
        environment:
            - ETHEREUM_HTTP=http://parity:8545
            - ETHEREUM_LIQUID_LONG_ADDRESS=0xF3BCABD8FAE29F75BE271EBE2499EDB4C7C139B7

    client-library-geth:
        build: ./client-library
        links:
            - geth
        environment:
            - ETHEREUM_HTTP=http://geth:8545
            - ETHEREUM_LIQUID_LONG_ADDRESS=0xF3BCABD8FAE29F75BE271EBE2499EDB4C7C139B7
